sudo: required

language: php

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install curl
  - docker build -t friendlyhello .
  - docker run -d -p 4000:80 friendlyhello
  - ip addr # for confirmation. can be skipped

script:
  - ./test.sh
  