sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install curl
  - docker build -t friendlyhello .
  - docker run -d -p 4000:80 friendlyhello

script:
  - test.sh
  